version: '3.8'

services:
  web:
    build:
      context: ./glitch
    ports:
      - "8081:8081"
    volumes:
      - .:/glitch

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - .:/server

  mobile:
    build:
      context: ./glitch
    ports:
      - "19000:19000" # Expo DevTools port
      - "19001:19001" # Expo project tunnel
      - "19002:19002" # Metro Bundler
    volumes:
      - .:/mobile
    command: ["npx", "expo", "start", "--tunnel"]
