version: '3.8'

services:
  web:
    build:
      context: ./glitch
    ports:
      - "8081:8081"
    volumes:
      - .:/glitch

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - .:/server
